default_platform(:android)

platform :android do
  desc "Upload to Google Play Store"
  lane :deploy do |options|
    timestamp = Time.now.strftime("%Y-%m-%d %H:%M:%S")
    
    upload_to_play_store(
      package_name: "com.hogan.kang.storetest",
      track: "internal",
      release_status: "draft",
      aab: "app/build/outputs/bundle/release/app-release-signed.aab",
      # 显式声明不保留旧版本，从而达到“替换”的效果
      version_codes_to_retain: [], 
      check_superseded_tracks: true,
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      release_notes: {
        "en-US" => "Automated release at #{timestamp}"
      }
    )
  end
end
